version: "3"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    ports:
      - "32000:3310"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro